services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411" # Zipkin UI

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - zipkin-all-in-one
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver

  go-location-finder:
    container_name: go-location-finder
    build:
      context: ./go-location-finder
      dockerfile: Dockerfile
    env_file:
      - ./go-location-finder/.env
    environment:
      - TITLE=Microservice go-location-finder
      - CONTENT=This is a demo of a microservice
      - RESPONSE_TIME=10000
      - REQUEST_NAME_OTEL=go-location-finder
      - OTEL_SERVICE_NAME=go-location-finder
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      - zipkin-all-in-one
      - otel-collector

  go-location-validator:
    container_name: go-location-validator
    build:
      context: ./go-location-validator
      dockerfile: Dockerfile
    environment:
      - TITLE=Microservice go-location-validator
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=blue
      - EXTERNAL_CALL_URL=http://go-location-finder:8080/cep
      - EXTERNAL_CALL_METHOD=POST
      - RESPONSE_TIME=10000
      - REQUEST_NAME_OTEL=microservice-go-location-validator
      - OTEL_SERVICE_NAME=microservice-go-location-validator
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:9000
    depends_on:
      - go-location-finder
      - otel-collector
    ports:
      - "9000:9000"
