@baseUrlDev = http://localhost:9000
@baseUrlProd = http://go-location-validator:9000
@cepEndpoint = /validate


###
POST {{baseUrlProd}}{{cepEndpoint}}
Content-Type: application/json

{
    "cep": "29090-040"
}

