@baseUrl = http://localhost:9000
@cepEndpoint = /validate


###
POST {{baseUrl}}{{cepEndpoint}}
Content-Type: application/json

{
    "cep": "23456-110"
}

###

POST http://localhost:8080/cep
Content-Type: application/json

{
    "cep": "12237-010"
}